### ISSUE TITLE
Runtime Exception after Install

### ISSUE THREAD

**Issue by ReneReiterer** [xima-media/xima-typo3-frontend-edit#4]
Hey, 

i just installed your extension on a 12.4 installation and Included the static TypoScript template but when i open my site i get this error: 

#1639819692 RuntimeException
ViewHelper f:uri.action can be used only in extbase context and needs a request implementing extbase RequestInterface.

The extension is installed via the extensions module in the backend

Cache is cleared.

**Comment by jackd248** [comment]
Thanks for the report, I will check this.

**Comment by ReneReiterer** [comment]
No problem, if you need more info, just let me know

**Comment by jackd248** [comment]
Actually I wasn't able to recreate this issue with a clean TYPO3 v12 non-composer mode installation. (using the repo: [ddev-typo3-src](https://github.com/GsTYPO3/ddev-typo3-src)).

I also don't quite understand why the Extbase context should not be available in your frontend. Are there any particular reasons for this in your project?

**Comment by ReneReiterer** [comment]
Fixed it, seems like it a problem with earlier typo3 v12 versions. I had 12.4.4 installed, now that i have 12.4.19 it works. 
Could have to do with this, but i am not sure https://review.typo3.org/c/Packages/TYPO3.CMS/+/80908

**Comment by jackd248** [comment]
Good to know, but I think to refactor the link generation process to avoid using the viewhelper.
