### ISSUE TITLE
Icon alignment in edit button

### ISSUE THREAD

**Issue by maikschneider** [xima-media/xima-typo3-frontend-edit#6]
I have very litte default styles for the `button` or `svg` element. In my installation the icon is not horizontally aligned:

![Screenshot 2024-09-05 at 16 06 08](https://github.com/user-attachments/assets/05cc308a-1d68-4bfe-b1fa-7a2c40daf7ac)

**Comment by jackd248** [comment]
Was fixed with b8ba43d
